export const ONE23 = ['1', '2', '3']

export const COMPLEMENUARY_MAP = {
  G:'C',
  A:'U',
  U:'A',
  C:'G',
}
//set G to high note to establish irrechlar pulse
export const BASE_MAP = {
  A: 0,
  U: 1,
  G: 2,
  C: 3,
}

export const NSP_MAP = {
  A: 2,
  U: 3,
  G: 0,
  C: 1,
}

export const TWOBASE_MAP = {
  AA: 0,
  UU: 1,
  AU: 2,
  UA: 3,
  UG: 4,
  CA: 5,
  CU: 6,
  AG: 7,
  UC: 8,
  GA: 9,
  GU: 10,
  AC: 11,
  CG: 12,
  GC: 13,
  CC: 14,
  GG: 15,
}

export const CODON_MAP =
{
  AUA: {AA: 'Ile', Note: 0, AA1: '-I-'},
  AUU: {AA: 'Ile', Note: 0, AA1: '-I-'},
  AUC: {AA: 'Ile', Note: 0, AA1: '-I-'},
  AAU: {AA: 'Asn', Note: 1, AA1: '-N-'},
  AAC: {AA: 'Asn', Note: 1, AA1: '-N-'},
  UAU: {AA: 'Tyr', Note: 2, AA1: '-Y-'},
  UAC: {AA: 'Tyr', Note: 2, AA1: '-Y-'},
  AAA: {AA: 'Lys', Note: 3, AA1: '-K-'},
  AAG: {AA: 'Lys', Note: 3, AA1: '-K-'},
  UUU: {AA: 'Phe', Note: 4, AA1: '-F-'},
  UUC: {AA: 'Phe', Note: 4, AA1: '-F-'},
  UUA: {AA: 'Leu', Note: 5, AA1: '-L-'},
  CUA: {AA: 'Leu', Note: 5, AA1: '-L-'},
  CUU: {AA: 'Leu', Note: 5, AA1: '-L-'},
  UUG: {AA: 'Leu', Note: 5, AA1: '-L-'},
  CUC: {AA: 'Leu', Note: 5, AA1: '-L-'},
  CUG: {AA: 'Leu', Note: 5, AA1: '-L-'},
  ACA: {AA: 'Thr', Note: 6, AA1: '-T-'},
  ACU: {AA: 'Thr', Note: 6, AA1: '-T-'},
  ACC: {AA: 'Thr', Note: 6, AA1: '-T-'},
  ACG: {AA: 'Thr', Note: 6, AA1: '-T-'},
  GUA: {AA: 'Val', Note: 7, AA1: '-V-'},
  GUU: {AA: 'Val', Note: 7, AA1: '-V-'},
  GUC: {AA: 'Val', Note: 7, AA1: '-V-'},
  GUG: {AA: 'Val', Note: 7, AA1: '-V-'},
  GAU: {AA: 'Asp', Note: 8, AA1: '-N-'},
  GAC: {AA: 'Asp', Note: 8, AA1: '-N-'},
  UGU: {AA: 'Cys', Note: 9, AA1: '-C-'},
  UGC: {AA: 'Cys', Note: 9, AA1: '-C-'},
  CAA: {AA: 'Gln', Note: 10, AA1: '-Q-'},
  CAG: {AA: 'Gln', Note: 10, AA1: '-Q-'},
  GAA: {AA: 'Glu', Note: 11, AA1: '-E-'},
  GAG: {AA: 'Glu', Note: 11, AA1: '-E-'},
  CAU: {AA: 'His', Note: 12, AA1: '-H-'},
  CAC: {AA: 'His', Note: 12, AA1: '-H-'},
  AGU: {AA: 'Ser', Note: 13, AA1: '-S-'},
  UCA: {AA: 'Ser', Note: 13, AA1: '-S-'},
  UCU: {AA: 'Ser', Note: 13, AA1: '-S-'},
  AGC: {AA: 'Ser', Note: 13, AA1: '-S-'},
  UCC: {AA: 'Ser', Note: 13, AA1: '-S-'},
  UCG: {AA: 'Ser', Note: 13, AA1: '-S-'},
  UGG: {AA: 'Trp', Note: 14, AA1: '-W-'},
  AGA: {AA: 'Arg', Note: 15, AA1: '-R-'},
  AGG: {AA: 'Arg', Note: 15, AA1: '-R-'},
  CGA: {AA: 'Arg', Note: 15, AA1: '-R-'},
  CGU: {AA: 'Arg', Note: 15, AA1: '-R-'},
  CGC: {AA: 'Arg', Note: 15, AA1: '-R-'},
  CGG: {AA: 'Arg', Note: 15, AA1: '-R-'},
  CCA: {AA: 'Pro', Note: 16, AA1: '-P-'},
  CCU: {AA: 'Pro', Note: 16, AA1: '-P-'},
  CCC: {AA: 'Pro', Note: 16, AA1: '-P-'},
  CCG: {AA: 'Pro', Note: 16, AA1: '-P-'},
  GCA: {AA: 'Ala', Note: 17, AA1: '-A-'},
  GCU: {AA: 'Ala', Note: 17, AA1: '-A-'},
  GCC: {AA: 'Ala', Note: 17, AA1: '-A-'},
  GCG: {AA: 'Ala', Note: 17, AA1: '-A-'},
  GGA: {AA: 'Gly', Note: 18, AA1: '-G-'},
  GGU: {AA: 'Gly', Note: 18, AA1: '-G-'},
  GGC: {AA: 'Gly', Note: 18, AA1: '-G-'},
  GGG: {AA: 'Gly', Note: 18, AA1: '-G-'},
  UAA: {AA: 'ST*', Note: 19, AA1: ' - '},
  UAG: {AA: 'ST*', Note: 19, AA1: ' - '},
  UGA: {AA: 'ST*', Note: 19, AA1: ' - '},
  AUG: {AA: 'Mt*', Note: 20, AA1: '-M-'},
}

// chromatic? 64 note range
// Microtonal
export const CODON_MAP_2 = {
  GGG: {AA: null, Note: 0},
  AUA: {AA: null, Note: 1},
  AUU: {AA: null, Note: 2},
  AAU: {AA: null, Note: 3},
  UAU: {AA: null, Note: 4},
  AAA: {AA: null, Note: 5},
  UUU: {AA: null, Note: 6},
  UAA: {AA: null, Note: 7},
  UUA: {AA: null, Note: 8},
  AUC: {AA: null, Note: 9},
  AAC: {AA: null, Note: 10},
  UAC: {AA: null, Note: 11},
  AAG: {AA: null, Note: 12},
  UUC: {AA: null, Note: 13},
  UAG: {AA: null, Note: 14},
  UGA: {AA: null, Note: 15},
  AUG: {AA: null, Note: 16},
  CUA: {AA: null, Note: 17},
  CUU: {AA: null, Note: 18},
  UUG: {AA: null, Note: 19},
  ACA: {AA: null, Note: 20},
  ACU: {AA: null, Note: 21},
  GUA: {AA: null, Note: 22},
  GUU: {AA: null, Note: 23},
  GAU: {AA: null, Note: 24},
  UGU: {AA: null, Note: 25},
  CAA: {AA: null, Note: 26},
  GAA: {AA: null, Note: 27},
  CAU: {AA: null, Note: 28},
  AGU: {AA: null, Note: 29},
  UCA: {AA: null, Note: 30},
  UCU: {AA: null, Note: 31},
  AGA: {AA: null, Note: 32},
  CUC: {AA: null, Note: 33},
  CUG: {AA: null, Note: 34},
  ACC: {AA: null, Note: 35},
  ACG: {AA: null, Note: 36},
  GUC: {AA: null, Note: 37},
  GUG: {AA: null, Note: 38},
  GAC: {AA: null, Note: 39},
  UGC: {AA: null, Note: 40},
  CAG: {AA: null, Note: 41},
  GAG: {AA: null, Note: 42},
  CAC: {AA: null, Note: 43},
  AGC: {AA: null, Note: 44},
  UCC: {AA: null, Note: 45},
  UCG: {AA: null, Note: 46},
  UGG: {AA: null, Note: 47},
  AGG: {AA: null, Note: 48},
  CGA: {AA: null, Note: 49},
  CGU: {AA: null, Note: 50},
  CCA: {AA: null, Note: 51},
  CCU: {AA: null, Note: 52},
  GCA: {AA: null, Note: 53},
  GCU: {AA: null, Note: 54},
  GGA: {AA: null, Note: 55},
  GGU: {AA: null, Note: 56},
  CGC: {AA: null, Note: 57},
  CGG: {AA: null, Note: 58},
  CCC: {AA: null, Note: 59},
  CCG: {AA: null, Note: 60},
  GCC: {AA: null, Note: 61},
  GCG: {AA: null, Note: 62},
  GGC: {AA: null, Note: 63},
}
