export const ONE23 = ['1', '2', '3']

export const COMPLEMENUARY_MAP = {
  G:'C',
  A:'U',
  U:'A',
  C:'G'
}

export const ANTICODON_MAP = {
  G:'C',
  A:'U',
  U:'A',
  C:'G'
}

export const BASE_MAP = {
  G: 'C2',
  A: 'E2',
  U: 'G2',
  C: 'C3'
}

export const TRS_MAP = {
  G: 'C5',
  A: 'E5',
  U: 'G5',
  C: 'B6'
}

export const TWOBASE_MAP = {
  UG: 'C1',
  UA: 'E1',
  UU: 'G1',
  UC: 'B2',
  CG: 'C2',
  CA: 'E2',
  CU: 'G2',
  CC: 'B3',
  GG: 'C3',
  GA: 'E3',
  GU: 'G3',
  GC: 'B4',
  AG: 'C4',
  AA: 'E4',
  AU: 'G4',
  AC: 'B5'
}

// export const CODON_MAP = {
//   GCA: 'C2',
//   GCC: 'C2',
//   GCG: 'C2',
//   GCU: 'C2',
//   AGA: 'D2',
//   AGG: 'D2',
//   CGA: 'D2',
//   CGC: 'D2',
//   CGG: 'D2',
//   CGU: 'D2',
//   AAC: 'E2',
//   AAU: 'E2',
//   GAC: 'F2',
//   GAU: 'F2',
//   UGC: 'G2',
//   UGU: 'G2',
//   CAA: 'A3',
//   CAG: 'A3',
//   GAA: 'B3',
//   GAG: 'B3',
//   GGA: 'C3',
//   GGC: 'C3',
//   GGG: 'C3',
//   GGU: 'C3',
//   CAC: 'C3',
//   CAU: 'C3',
//   AUA: 'D3',
//   AUC: 'D3',
//   AUU: 'D3',
//   CUA: 'E3',
//   CUC: 'E3',
//   CUG: 'E3',
//   CUU: 'E3',
//   UUA: 'E3',
//   UUG: 'E3',
//   AAA: 'F3',
//   AAG: 'F3',
//   AUG: 'G3',
//   UUC: 'A4',
//   UUU: 'A4',
//   CCA: 'B4',
//   CCC: 'B4',
//   CCG: 'B4',
//   CCU: 'B4',
//   AGC: 'C4',
//   AGU: 'C4',
//   UCA: 'C4',
//   UCC: 'C4',
//   UCG: 'C4',
//   UCU: 'C4',
//   UAA: 'D4',
//   UAG: 'D4',
//   UGA: 'D4',
//   ACA: 'E4',
//   ACC: 'E4',
//   ACG: 'E4',
//   ACU: 'E4',
//   UGG: 'F4',
//   UAC: 'F4',
//   UAU: 'F4',
//   GUA: 'G4',
//   GUC: 'G4',
//   GUG: 'G4',
//   GUU: 'G4'
// }
/*
https://regexr.com/
example bre tata AGAAAGAUUAAAAG
(?:[ag][agc]aaa[ag])(a{1,3})(?:ttaaa[at][ag])
*/

export const CODON_MAP2 = {
GCA:{AA:'Ala',Note:'C2'},
GCC:{AA:'Ala',Note:'C2'},
GCG:{AA:'Ala',Note:'C2'},
GCU:{AA:'Ala',Note:'C2'},
AGA:{AA:'Arg',Note:'D2'},
AGG:{AA:'Arg',Note:'D2'},
CGA:{AA:'Arg',Note:'D2'},
CGC:{AA:'Arg',Note:'D2'},
CGG:{AA:'Arg',Note:'D2'},
CGU:{AA:'Arg',Note:'D2'},
AAC:{AA:'Asn',Note:'E2'},
AAU:{AA:'Asn',Note:'E2'},
GAC:{AA:'Asp',Note:'F2'},
GAU:{AA:'Asp',Note:'F2'},
UGC:{AA:'Cys',Note:'G2'},
UGU:{AA:'Cys',Note:'G2'},
CAA:{AA:'Gln',Note:'A3'},
CAG:{AA:'Gln',Note:'A3'},
GAA:{AA:'Glu',Note:'B3'},
GAG:{AA:'Glu',Note:'B3'},
GGA:{AA:'Gly',Note:'C3'},
GGC:{AA:'Gly',Note:'C3'},
GGG:{AA:'Gly',Note:'C3'},
GGU:{AA:'Gly',Note:'C3'},
CAC:{AA:'His',Note:'C3'},
CAU:{AA:'His',Note:'C3'},
AUA:{AA:'Ile',Note:'D3'},
AUC:{AA:'Ile',Note:'D3'},
AUU:{AA:'Ile',Note:'D3'},
CUA:{AA:'Leu',Note:'E3'},
CUC:{AA:'Leu',Note:'E3'},
CUG:{AA:'Leu',Note:'E3'},
CUU:{AA:'Leu',Note:'E3'},
UUA:{AA:'Leu',Note:'E3'},
UUG:{AA:'Leu',Note:'E3'},
AAA:{AA:'Lys',Note:'F3'},
AAG:{AA:'Lys',Note:'F3'},
AUG:{AA:'Mt*',Note:'G3'},
UUC:{AA:'Phe',Note:'A4'},
UUU:{AA:'Phe',Note:'A4'},
CCA:{AA:'Pro',Note:'B4'},
CCC:{AA:'Pro',Note:'B4'},
CCG:{AA:'Pro',Note:'B4'},
CCU:{AA:'Pro',Note:'B4'},
AGC:{AA:'Ser',Note:'C4'},
AGU:{AA:'Ser',Note:'C4'},
UCA:{AA:'Ser',Note:'C4'},
UCC:{AA:'Ser',Note:'C4'},
UCG:{AA:'Ser',Note:'C4'},
UCU:{AA:'Ser',Note:'C4'},
UAA:{AA:'ST*',Note:'D4'},
UAG:{AA:'ST*',Note:'D4'},
UGA:{AA:'ST*',Note:'D4'},
ACA:{AA:'Thr',Note:'E4'},
ACC:{AA:'Thr',Note:'E4'},
ACG:{AA:'Thr',Note:'E4'},
ACU:{AA:'Thr',Note:'E4'},
UGG:{AA:'Trp',Note:'F4'},
UAC:{AA:'Tyr',Note:'F4'},
UAU:{AA:'Tyr',Note:'F4'},
GUA:{AA:'Val',Note:'G4'},
GUC:{AA:'Val',Note:'G4'},
GUG:{AA:'Val',Note:'G4'},
GUU:{AA:'Val',Note:'G4'}
}
